dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install: pip install -U pip coveralls
install: pip install .[test]
script: pytest -Wd --cov mailshake --cov tests .
after_success: coveralls
